#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO_PieChart
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarManagement")]
	public partial class CarDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCAR(CAR instance);
    partial void UpdateCAR(CAR instance);
    partial void DeleteCAR(CAR instance);
    partial void InsertBUY(BUY instance);
    partial void UpdateBUY(BUY instance);
    partial void DeleteBUY(BUY instance);
    #endregion
		
		public CarDataDataContext() : 
				base(global::DEMO_PieChart.Properties.Settings.Default.CarManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CAR> CARs
		{
			get
			{
				return this.GetTable<CAR>();
			}
		}
		
		public System.Data.Linq.Table<BUY> BUYs
		{
			get
			{
				return this.GetTable<BUY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAR")]
	public partial class CAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CAR_ID;
		
		private string _CAR_NAME;
		
		private string _CAR_BRAND;
		
		private System.Nullable<char> _CAR_TYPE;
		
		private string _CAR_DESCRIBE;
		
		private System.Nullable<decimal> _CAR_PRICE;
		
		private System.Nullable<int> _CAR_QUANTITY;
		
		private string _CAR_IMAGE;
		
		private EntitySet<BUY> _BUYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCAR_IDChanging(int value);
    partial void OnCAR_IDChanged();
    partial void OnCAR_NAMEChanging(string value);
    partial void OnCAR_NAMEChanged();
    partial void OnCAR_BRANDChanging(string value);
    partial void OnCAR_BRANDChanged();
    partial void OnCAR_TYPEChanging(System.Nullable<char> value);
    partial void OnCAR_TYPEChanged();
    partial void OnCAR_DESCRIBEChanging(string value);
    partial void OnCAR_DESCRIBEChanged();
    partial void OnCAR_PRICEChanging(System.Nullable<decimal> value);
    partial void OnCAR_PRICEChanged();
    partial void OnCAR_QUANTITYChanging(System.Nullable<int> value);
    partial void OnCAR_QUANTITYChanged();
    partial void OnCAR_IMAGEChanging(string value);
    partial void OnCAR_IMAGEChanged();
    #endregion
		
		public CAR()
		{
			this._BUYs = new EntitySet<BUY>(new Action<BUY>(this.attach_BUYs), new Action<BUY>(this.detach_BUYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CAR_ID
		{
			get
			{
				return this._CAR_ID;
			}
			set
			{
				if ((this._CAR_ID != value))
				{
					this.OnCAR_IDChanging(value);
					this.SendPropertyChanging();
					this._CAR_ID = value;
					this.SendPropertyChanged("CAR_ID");
					this.OnCAR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_NAME", DbType="NVarChar(100)")]
		public string CAR_NAME
		{
			get
			{
				return this._CAR_NAME;
			}
			set
			{
				if ((this._CAR_NAME != value))
				{
					this.OnCAR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CAR_NAME = value;
					this.SendPropertyChanged("CAR_NAME");
					this.OnCAR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_BRAND", DbType="NVarChar(100)")]
		public string CAR_BRAND
		{
			get
			{
				return this._CAR_BRAND;
			}
			set
			{
				if ((this._CAR_BRAND != value))
				{
					this.OnCAR_BRANDChanging(value);
					this.SendPropertyChanging();
					this._CAR_BRAND = value;
					this.SendPropertyChanged("CAR_BRAND");
					this.OnCAR_BRANDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_TYPE", DbType="Char(1)")]
		public System.Nullable<char> CAR_TYPE
		{
			get
			{
				return this._CAR_TYPE;
			}
			set
			{
				if ((this._CAR_TYPE != value))
				{
					this.OnCAR_TYPEChanging(value);
					this.SendPropertyChanging();
					this._CAR_TYPE = value;
					this.SendPropertyChanged("CAR_TYPE");
					this.OnCAR_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_DESCRIBE", DbType="NVarChar(300)")]
		public string CAR_DESCRIBE
		{
			get
			{
				return this._CAR_DESCRIBE;
			}
			set
			{
				if ((this._CAR_DESCRIBE != value))
				{
					this.OnCAR_DESCRIBEChanging(value);
					this.SendPropertyChanging();
					this._CAR_DESCRIBE = value;
					this.SendPropertyChanged("CAR_DESCRIBE");
					this.OnCAR_DESCRIBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_PRICE", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CAR_PRICE
		{
			get
			{
				return this._CAR_PRICE;
			}
			set
			{
				if ((this._CAR_PRICE != value))
				{
					this.OnCAR_PRICEChanging(value);
					this.SendPropertyChanging();
					this._CAR_PRICE = value;
					this.SendPropertyChanged("CAR_PRICE");
					this.OnCAR_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_QUANTITY", DbType="Int")]
		public System.Nullable<int> CAR_QUANTITY
		{
			get
			{
				return this._CAR_QUANTITY;
			}
			set
			{
				if ((this._CAR_QUANTITY != value))
				{
					this.OnCAR_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._CAR_QUANTITY = value;
					this.SendPropertyChanged("CAR_QUANTITY");
					this.OnCAR_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_IMAGE", DbType="VarChar(100)")]
		public string CAR_IMAGE
		{
			get
			{
				return this._CAR_IMAGE;
			}
			set
			{
				if ((this._CAR_IMAGE != value))
				{
					this.OnCAR_IMAGEChanging(value);
					this.SendPropertyChanging();
					this._CAR_IMAGE = value;
					this.SendPropertyChanged("CAR_IMAGE");
					this.OnCAR_IMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAR_BUY", Storage="_BUYs", ThisKey="CAR_ID", OtherKey="CAR_ID")]
		public EntitySet<BUY> BUYs
		{
			get
			{
				return this._BUYs;
			}
			set
			{
				this._BUYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BUYs(BUY entity)
		{
			this.SendPropertyChanging();
			entity.CAR = this;
		}
		
		private void detach_BUYs(BUY entity)
		{
			this.SendPropertyChanging();
			entity.CAR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BUY")]
	public partial class BUY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BUY_ID;
		
		private string _CUSTOMER_ID;
		
		private System.Nullable<int> _CAR_ID;
		
		private System.Nullable<int> _BUY_QUANTITY;
		
		private System.Nullable<System.DateTime> _BUY_DATE;
		
		private EntityRef<CAR> _CAR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBUY_IDChanging(int value);
    partial void OnBUY_IDChanged();
    partial void OnCUSTOMER_IDChanging(string value);
    partial void OnCUSTOMER_IDChanged();
    partial void OnCAR_IDChanging(System.Nullable<int> value);
    partial void OnCAR_IDChanged();
    partial void OnBUY_QUANTITYChanging(System.Nullable<int> value);
    partial void OnBUY_QUANTITYChanged();
    partial void OnBUY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBUY_DATEChanged();
    #endregion
		
		public BUY()
		{
			this._CAR = default(EntityRef<CAR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUY_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BUY_ID
		{
			get
			{
				return this._BUY_ID;
			}
			set
			{
				if ((this._BUY_ID != value))
				{
					this.OnBUY_IDChanging(value);
					this.SendPropertyChanging();
					this._BUY_ID = value;
					this.SendPropertyChanged("BUY_ID");
					this.OnBUY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_ID", DbType="Char(9)")]
		public string CUSTOMER_ID
		{
			get
			{
				return this._CUSTOMER_ID;
			}
			set
			{
				if ((this._CUSTOMER_ID != value))
				{
					this.OnCUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_ID = value;
					this.SendPropertyChanged("CUSTOMER_ID");
					this.OnCUSTOMER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAR_ID", DbType="Int")]
		public System.Nullable<int> CAR_ID
		{
			get
			{
				return this._CAR_ID;
			}
			set
			{
				if ((this._CAR_ID != value))
				{
					if (this._CAR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCAR_IDChanging(value);
					this.SendPropertyChanging();
					this._CAR_ID = value;
					this.SendPropertyChanged("CAR_ID");
					this.OnCAR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUY_QUANTITY", DbType="Int")]
		public System.Nullable<int> BUY_QUANTITY
		{
			get
			{
				return this._BUY_QUANTITY;
			}
			set
			{
				if ((this._BUY_QUANTITY != value))
				{
					this.OnBUY_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._BUY_QUANTITY = value;
					this.SendPropertyChanged("BUY_QUANTITY");
					this.OnBUY_QUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUY_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> BUY_DATE
		{
			get
			{
				return this._BUY_DATE;
			}
			set
			{
				if ((this._BUY_DATE != value))
				{
					this.OnBUY_DATEChanging(value);
					this.SendPropertyChanging();
					this._BUY_DATE = value;
					this.SendPropertyChanged("BUY_DATE");
					this.OnBUY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAR_BUY", Storage="_CAR", ThisKey="CAR_ID", OtherKey="CAR_ID", IsForeignKey=true)]
		public CAR CAR
		{
			get
			{
				return this._CAR.Entity;
			}
			set
			{
				CAR previousValue = this._CAR.Entity;
				if (((previousValue != value) 
							|| (this._CAR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAR.Entity = null;
						previousValue.BUYs.Remove(this);
					}
					this._CAR.Entity = value;
					if ((value != null))
					{
						value.BUYs.Add(this);
						this._CAR_ID = value.CAR_ID;
					}
					else
					{
						this._CAR_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("CAR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
