<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataForPieChartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="DEMO_PieChart.Properties.Settings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BUY" Member="BUYs">
    <Type Name="BUY">
      <Column Name="BUY_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CUSTOMER_ID" Type="System.String" DbType="Char(9)" CanBeNull="true" />
      <Column Name="CAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BUY_QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BUY_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="CAR_BUY" Member="CAR" ThisKey="CAR_ID" OtherKey="CAR_ID" Type="CAR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAR" Member="CARs">
    <Type Name="CAR">
      <Column Name="CAR_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CAR_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CAR_BRAND" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CAR_TYPE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CAR_DESCRIBE" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CAR_PRICE" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="CAR_QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAR_IMAGE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="CAR_BUY" Member="BUYs" ThisKey="CAR_ID" OtherKey="CAR_ID" Type="BUY" />
    </Type>
  </Table>
</Database>